apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q7ein2ld8-java-quarkus
  janus-idp.io/tekton: q7ein2ld8-java-quarkus
  backstage.io/kubernetes-id: q7ein2ld8-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q7ein2ld8-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
